version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Installing dependencies...

  build:
    commands:
      - echo Build started on `date`
      # Add your build commands here, e.g., npm build, docker build, etc.
      - echo Build completed on `date`

  post_build:
    commands:
      - echo Updating ECS service to force new deployment...
      - |
        aws ecs update-service --region ap-south-1 --cluster capstone-cluster --service capstone-service --force-new-deployment --network-configuration "awsvpcConfiguration={subnets=[subnet-06a1ae09aaf775b8f],securityGroups=[sg-029beaf9489126e73],assignPublicIp=ENABLED}"

artifacts:
  files:
    - '**/*'
