version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt  # if applicable

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 528757813453.dkr.ecr.ap-south-1.amazonaws.com

  build:
    commands:
      - echo Building Docker image...
      - docker build -t frontend-repo .
      - docker tag frontend-repo:latest 528757813453.dkr.ecr.ap-south-1.amazonaws.com/frontend-repo:latest

  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push 528757813453.dkr.ecr.ap-south-1.amazonaws.com/frontend-repo:latest
      - echo Updating ECS service...
      - aws ecs update-service \
          --region ap-south-1 \
          --cluster capstone-cluster \
          --service capstone-service \
          --force-new-deployment \
          --network-configuration '{"awsvpcConfiguration":{"subnets":["subnet-06a1ae09aaf775b8f"],"securityGroups":["sg-03b955ab41b2ea944"],"assignPublicIp":"ENABLED"}}'

artifacts:
  files:
    - '**/*'
