version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt || true  # if you have requirements.txt

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 528757813453.dkr.ecr.ap-south-1.amazonaws.com
      - REPOSITORY_URI=528757813453.dkr.ecr.ap-south-1.amazonaws.com/frontend-repo
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)

  build:
    commands:
      - echo Building Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .

  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Updating ECS service...
      - aws ecs update-service \
          --region ap-south-1 \
          --cluster capstone-cluster \
          --service capstone-service \
          --force-new-deployment \
          --network-configuration '{"awsvpcConfiguration": {"subnets": ["subnet-06a1ae09aaf775b8f"], "securityGroups": ["sg-029beaf9489126e73"], "assignPublicIp": "ENABLED"}}'

artifacts:
  files:
    - '**/*'
